name: Continuous Integration

on:
  push:
    branches: [ main, MERGED ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    name: Build & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, sqlite3, pdo_sqlite, gd
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Build Frontend Assets
        run: npm run build

      - name: Prepare Environment & SQLite DB
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
